# Generated by Django 6.0.1 on 2026-05-21 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_role_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_notifications_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Kada vartotojas paskutinį kartą peržiūrėjo pranešimus'),
        ),
    ]
