# Generated by Django 6.0.1 on 2026-05-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_last_notifications_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Ar vartotojas patvirtino savo el. paštą per laišką'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='Kada paskutinį kartą išsiųstas patvirtinimo laiškas', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(blank=True, help_text="Token'as siunčiamas su patvirtinimo nuoroda", max_length=128),
        ),
    ]
