# Generated by Django 6.0.1 on 2026-05-28 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_email_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profilis', 'verbose_name_plural': 'Profiliai'},
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='kind',
            field=models.CharField(choices=[('verification', 'Email patvirtinimas'), ('training_cancelled', 'Treniruotė atšaukta'), ('reminder_day', 'Priminimas (24h)'), ('reminder_hour', 'Priminimas (1h)'), ('membership_expiring', 'Abonementas baigsis')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='El. paštas patvirtintas'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_notifications_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paskutinį kartą peržiūrėjo pranešimus'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Klientas'), ('TRAINER', 'Treneris'), ('ADMIN', 'Administratorius')], default='CLIENT', max_length=10, verbose_name='Rolė'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token sukurtas'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Patvirtinimo token'),
        ),
    ]
