# Generated by Django 6.0.1 on 2026-01-09 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField(help_text='Abonemento galiojimo trukmė dienomis')),
                ('visit_limit', models.PositiveIntegerField(blank=True, help_text='Apsilankymų limitas (jei nėra – neribotas)', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktyvus'), ('EXPIRED', 'Pasibaigęs'), ('PAUSED', 'Sustabdyta')], default='ACTIVE', max_length=10)),
                ('visits_left', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.membershipplan')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Laukiama apmokėjimo'), ('PAID', 'Apmokėta'), ('REJECTED', 'Atmesta')], default='PENDING', max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='Nuoroda į treniruotės paveikslą (URL)')),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planuojama'), ('CANCELLED', 'Atšaukta')], default='SCHEDULED', max_length=10)),
                ('cancellation_note', models.CharField(blank=True, max_length=255)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'Užregistruota'), ('CANCELLED', 'Atšaukta'), ('ATTENDED', 'Dalyvavo'), ('NO_SHOW', 'Neatvyko')], default='BOOKED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gym.training')),
            ],
            options={
                'unique_together': {('training', 'user')},
            },
        ),
    ]
