# Generated by Django 6.0.1 on 2026-04-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Abonemento galiojimo trukmė dienomis'),
        ),
    ]
