# Generated by Django 6.0.1 on 2026-04-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_membershipplan_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippurchase',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Apmokėjimo data ir laikas', null=True),
        ),
        migrations.AddField(
            model_name='membershippurchase',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, help_text='Stripe mokėjimo ID', max_length=255),
        ),
        migrations.AddField(
            model_name='membershippurchase',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout sesijos ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
