# Generated by Django 6.0.1 on 2026-05-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_membershippurchase_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, help_text='Įkeltas paveikslėlio failas (jpg, png)', null=True, upload_to='trainings/'),
        ),
        migrations.AlterField(
            model_name='training',
            name='image_url',
            field=models.URLField(blank=True, help_text='Arba nuoroda į galerijos paveikslėlį'),
        ),
    ]
