# Generated by Django 6.0.1 on 2026-05-21 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_training_image_alter_training_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
