# Generated by Django 6.0.1 on 2026-05-28 21:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_training_created_at_alter_membershippurchase_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Narystė', 'verbose_name_plural': 'Narystės'},
        ),
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'verbose_name': 'Abonemento planas', 'verbose_name_plural': 'Abonementų planai'},
        ),
        migrations.AlterModelOptions(
            name='membershippurchase',
            options={'verbose_name': 'Pirkimas', 'verbose_name_plural': 'Pirkimai'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Rezervacija', 'verbose_name_plural': 'Rezervacijos'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Treniruotė', 'verbose_name_plural': 'Treniruotės'},
        ),
        migrations.AddField(
            model_name='training',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atšaukta'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sukurta'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(verbose_name='Pabaigos data'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.membershipplan', verbose_name='Planas'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Pradžios data'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktyvus'), ('EXPIRED', 'Pasibaigęs'), ('PAUSED', 'Sustabdyta')], default='ACTIVE', max_length=10, verbose_name='Būsena'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='visits_left',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Liko apsilankymų'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Abonemento galiojimo trukmė dienomis', verbose_name='Galiojimo trukmė (dienomis)'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Kaina (€)'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='visit_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Apsilankymų limitas (jei nėra – neribotas)', null=True, verbose_name='Apsilankymų limitas'),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sukurta'),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='Pilnas vardas'),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Apmokėjimo data'),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefonas'),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.membershipplan', verbose_name='Planas'),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Laukiama apmokėjimo'), ('PAID', 'Apmokėta'), ('REJECTED', 'Atmesta')], default='PENDING', max_length=10, verbose_name='Būsena'),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe mokėjimo ID'),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe sesijos ID'),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sukurta'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Užregistruota'), ('CANCELLED', 'Atšaukta'), ('ATTENDED', 'Dalyvavo'), ('NO_SHOW', 'Neatvyko')], default='BOOKED', max_length=10, verbose_name='Būsena'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gym.training', verbose_name='Treniruotė'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
        migrations.AlterField(
            model_name='training',
            name='cancellation_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Atšaukimo priežastis'),
        ),
        migrations.AlterField(
            model_name='training',
            name='capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='Talpa (žmonių)'),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sukurta'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Trukmė (min)'),
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, help_text='Įkeltas paveikslėlio failas (jpg, png)', null=True, upload_to='trainings/', verbose_name='Paveikslėlis'),
        ),
        migrations.AlterField(
            model_name='training',
            name='image_url',
            field=models.URLField(blank=True, help_text='Arba nuoroda į galerijos paveikslėlį', verbose_name='Paveikslėlio nuoroda'),
        ),
        migrations.AlterField(
            model_name='training',
            name='starts_at',
            field=models.DateTimeField(verbose_name='Pradžia'),
        ),
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Planuojama'), ('CANCELLED', 'Atšaukta')], default='SCHEDULED', max_length=10, verbose_name='Būsena'),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='Treneris'),
        ),
    ]
