# Generated by Django 6.0.1 on 2026-05-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='current_streak',
            field=models.PositiveIntegerField(default=0, help_text="Dabartinis dienų iš eilės streak'as (paskutinė dalyvavimo data + sekančios dienos)"),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_attendance_date',
            field=models.DateField(blank=True, help_text='Paskutinė data, kai dalyvavo treniruotėje', null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0, help_text="Ilgiausias streak'as kada nors pasiektas"),
        ),
    ]
